### ISSUE TITLE
BoundaryCallback doesn't work properly

### ISSUE THREAD

**Issue by roboticvn** [kaushiknsanji/PagingSampleCodelab_v1.x#2]
I see that the query function in DAO get data in sorting
```
@Query("SELECT * FROM repos WHERE (name LIKE :queryString) OR (description LIKE " +
            ":queryString) ORDER BY stars DESC, name ASC")
```
However, if I change query without sorting, BoundaryCallback doesn't work properly
`@Query("SELECT * FROM repos WHERE (name LIKE :queryString)")`
**onItemAtEndLoaded** seem to be called multiple times
Can you fix or explain this problem?

**Comment by kaushiknsanji** [comment]
Apologies for attending to this late. This repository is very much outdated since it is based on "Paging version 1.x". Hence closing this issue. Thank you for supporting this repository till date.
